### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by anhdpham** [stephenhky/MoguTDA#11]
Hi, I'm having this error when i tried to run a simple test code. I'm using python3.8

import numpy as np
from mogutda import SimplicialComplex

e1 = [(0, 1), (1, 2), (2, 0)]
sc1 = SimplicialComplex(e1)

print(sc1.betti_number(1))

ValueError                                Traceback (most recent call last)
Input In [11], in <cell line: 7>()
      4 e1 = [(0, 1), (1, 2), (2, 0)]
      5 sc1 = SimplicialComplex(e1)
----> 7 print(sc1.betti_number(1))

File ~\Anaconda3\envs\tda\lib\site-packages\mogutda\abssimcomplex.py:64, in SimplicialComplex.betti_number(self, i, eps)
     62 if eps is None:
     63     try:
---> 64         boundop_ip1_rank = np.linalg.matrix_rank(boundop_ip1.toarray())
     65     except np.linalg.LinAlgError:
     66         boundop_ip1_rank = boundop_ip1.shape[1]

File <__array_function__ internals>:180, in matrix_rank(*args, **kwargs)

File ~\Anaconda3\envs\tda\lib\site-packages\numpy\linalg\linalg.py:1900, in matrix_rank(A, tol, hermitian)
   1898 S = svd(A, compute_uv=False, hermitian=hermitian)
   1899 if tol is None:
-> 1900     tol = S.max(axis=-1, keepdims=True) * max(A.shape[-2:]) * finfo(S.dtype).eps
   1901 else:
   1902     tol = asarray(tol)[..., newaxis]

File ~\Anaconda3\envs\tda\lib\site-packages\numpy\core\_methods.py:40, in _amax(a, axis, out, keepdims, initial, where)
     38 def _amax(a, axis=None, out=None, keepdims=False,
     39           initial=_NoValue, where=True):
---> 40     return umr_maximum(a, axis, None, out, keepdims, initial, where)

ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by stephenhky** [comment]
Somehow I cannot reproduce the issue
`In [1]: import numpy as np

In [2]: from mogutda import SimplicialComplex

In [3]: e1 = [(0, 1), (1, 2), (2, 0)]
   ...: sc1 = SimplicialComplex(e1)

In [4]: sc1.betti_number(1)
Out[4]: 1

In [5]: sc1.betti_number(0)
Out[5]: 1`

**Comment by anhdpham** [comment]
Hi. I think it's the problem of Mac vs PC. The code works well on my Mac with python 3.8
