### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhuqunxi** [stephenhky/MoguTDA#4]
C:\Users\zhuqunxi>pip install mogutda
Collecting mogutda
  Using cached https://files.pythonhosted.org/packages/bb/4e/78e81217c3d8cef2c0bff47707d785e04594358a77b079f3fea8ac0e27a2/mogutda-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zhuqunxi\AppData\Local\Temp\pip-install-7fyvqvip\mogutda\setup.py", line 18, in <module>
        long_description=package_description(),
      File "C:\Users\zhuqunxi\AppData\Local\Temp\pip-install-7fyvqvip\mogutda\setup.py", line 10, in package_description
        text = open('README.md', 'r').read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 5556: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\zhuqunxi\AppData\Local\Temp\pip-install-7fyvqvip\mogutda\

**Comment by stephenhky** [comment]
Did you have any problems if you try the ordinary `pip install mogutda`?

**Comment by stephenhky** [comment]
I have no problems running `python setup.py egg_info` with Python 2.7 and Python 3.6 on my local Mac.

I did some research online, and it seems that your computer might have make "gbk" as the default codec. If you are using Python 2.7, you can change the above statement to `text = open('README.md', 'rb').read()` . However, if it is Python 3, I do not know. It is better to make the deault to be 'utf-8'.

**Comment by zhuqunxi** [comment]
I am using Python 3.6 in Win 10. I'll try to fix it. Great thanks for your kind answer.

**Comment by stephenhky** [comment]
Let me know how it goes then, esp if there are problems other than encoding.

**Comment by Rai-Rajat** [comment]
I encountered the same issue and fixed it by doing the following (For Windows 10):

Control Panel > Region > Administrative> Change system Locale > Check the box that says "Beta: Use Unicode UTF-8 for worldwide language support".

Once the computer restarted, I used pip to install mogutda from the terminal and it worked!
