### ISSUE TITLE
Persistence diagram of a clique complex

### ISSUE THREAD

**Issue by Nilsmiz** [stephenhky/MoguTDA#8]
Hi everybody,

I have seen a ton of codes to compute a persistence diagram when the input data is a point cloud. Is there a way to compute the persistence diagram of a filtration of a clique complex if the input data is a weighted graph? It cannot be done with the Ripser library right? Any code would be  very much appreciated. 

Thank you.

**Comment by stephenhky** [comment]
I didn't provide a persistence diagram code here. But I think it can be achieved by iterating over the filtration values
